BASEURL= ftp.ensemblgenomes.org/pub/release-52/plants

all:	Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz \
	Arabidopsis_thaliana.TAIR10.52.gtf.gz

Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz:
	wget $(BASEURL)/fasta/arabidopsis_thaliana/dna/$@

Arabidopsis_thaliana.TAIR10.52.gtf.gz:
	wget $(BASEURL)/gtf/arabidopsis_thaliana/dna/$@

# Genomes (fasta)
#wget ftp.ensemblgenomes.org/pub/release-52/plants/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/fasta/arabidopsis_lyrata/dna/Arabidopsis_lyrata.v.1.0.dna.toplevel.fa.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/fasta/arabidopsis_halleri/dna/Arabidopsis_halleri.Ahal2.2.dna.toplevel.fa.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/fasta/brassica_napus/dna/Brassica_napus.AST_PRJEB5043_v1.dna.toplevel.fa.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/fasta/brassica_rapa/dna/Brassica_rapa.Brapa_1.0.dna.toplevel.fa.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/fasta/brassica_oleracea/dna/Brassica_oleracea.BOL.dna.toplevel.fa.gz
# Genes (gtf)
#wget ftp.ensemblgenomes.org/pub/release-52/plants/gtf/arabidopsis_thaliana/Arabidopsis_thaliana.TAIR10.52.gtf.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/gtf/arabidopsis_lyrata/Arabidopsis_lyrata.v.1.0.52.gtf.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/gtf/arabidopsis_halleri/Arabidopsis_halleri.Ahal2.2.52.gtf.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/gtf/brassica_napus/Brassica_napus.AST_PRJEB5043_v1.52.gtf.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/gtf/brassica_rapa/Brassica_rapa.Brapa_1.0.52.gtf.gz
#wget ftp.ensemblgenomes.org/pub/release-52/plants/gtf/brassica_oleracea/Brassica_oleracea.BOL.52.gtf.gz
